### PR TITLE
Add pyobjc-framework-coreservices to run dependencies and update to v0.3.0

### PR DESCRIPTION
**Pull request by andfoy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andfoy** [comment]
@conda-forge-admin, please re-render

**Comment by andfoy** [comment]
@conda-forge-admin, please rerender

**Comment by andfoy** [comment]
@conda-forge/applaunchservices this one is ready for review

**Comment by ccordoba12** [comment]
Hey @impact27, thanks to @andfoy's help we have now coreservices in conda-forge, which will solve the dependency problems here and in Spyder as well.

**Comment by ccordoba12** [comment]
Thanks @goanpeca!

**Pull request merged**
