### PR TITLE
Increase minimal supported version to Python 3.8

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Older versions are quite old now.
- Also, add me as maintainer because this is core dependency for Spyder on Mac.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge/core, is this the right way to solve the following conflict to migrate Spyder to Python 3.12?

```
osx_arm64_python3.8.____cpython: Could not solve for environment specs
The following packages are incompatible
├─ applaunchservices >=0.3.0  is installable and it requires
│  └─ pyobjc-framework-coreservices with the potential options
│     ├─ pyobjc-framework-coreservices [8.5|8.5.1|9.0|9.1|9.2] would require
│     │  └─ python_abi 3.10.* *_cp310, which can be installed;
│     ├─ pyobjc-framework-coreservices [8.5|8.5.1|9.0|9.1|9.2] would require
│     │  └─ python_abi 3.11.* *_cp311, which can be installed;
│     ├─ pyobjc-framework-coreservices [8.5|8.5.1|9.0|9.1|9.2] would require
│     │  └─ pyobjc-framework-fsevents [9.2.* |>=8.5 |>=8.5.1 |>=9.0 |>=9.1 ] with the potential options
│     │     ├─ pyobjc-framework-fsevents [10.0|8.5|...|9.2] would require
│     │     │  └─ python_abi 3.10.* *_cp310, which can be installed;
│     │     ├─ pyobjc-framework-fsevents [10.0|8.5|...|9.2] would require
│     │     │  └─ python_abi 3.11.* *_cp311, which can be installed;
│     │     ├─ pyobjc-framework-fsevents [10.0|8.5|...|9.2] would require
│     │     │  └─ python_abi 3.9.* *_cp39, which can be installed;
│     │     └─ pyobjc-framework-fsevents [10.0|9.2] would require
│     │        └─ python >=3.12.0rc3,<3.13.0a0  with the potential options
│     │           ├─ python 3.12.0 would require
│     │           │  └─ python_abi 3.12.* *_cp312, which can be installed;
│     │           └─ python 3.12.0rc3 would require
│     │              └─ _python_rc, which does not exist (perhaps a missing channel);
│     ├─ pyobjc-framework-coreservices [8.5|8.5.1|9.0|9.1|9.2] would require
│     │  └─ python_abi 3.9.* *_cp39, which can be installed;
│     └─ pyobjc-framework-coreservices 9.2 would require
│        └─ python >=3.12,<3.13.0a0 , which can be installed (as previously explained);
├─ python >=3.8,<3.9.0a0  is not installable because it requires
│  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
└─ python_abi 3.8.* *_cp38 is not installable because it conflicts with any installable versions previously reported.
```

**Comment by ccordoba12** [comment]
And then asking for a migration of this package to arm64, of course.

**Comment by hmaarrfk** [comment]
why not keep the same monarch structure as before. it is 1 osx build instead of 8 and should still only install for osx and puthon greater than 3.8

**Comment by mbargull** [comment]
@hmaarrfk is right.
Since this package is `noarch: python`, it does not need to be migrated. (The bot should recognize this too.)

**Review by impact27 — APPROVED** [review]

**Comment by ccordoba12** [comment]
> why not keep the same monarch structure as before. it is 1 osx build instead of 8 and should still only install for osx and puthon greater than 3.8

The thing is we want to keep supporting Python 3.8 on Intel chips, and we can only support 3.9 on Arm ones due to the dependency on `pyobjc-framework-coreservices`.

But since you can't have selectors in noarch packages, I don't know how to achieve that in another way than what I did here.

**Comment by mbargull** [comment]
> The thing is we want to keep supporting Python 3.8 on Intel chips, and we can only support 3.9 on Arm ones due to the dependency on `pyobjc-framework-coreservices`.
> 
> But since you can't have selectors in noarch packages, I don't know how to achieve that in another way than what I did here.

You're already set with the current package builds.
1. With your proposed changes:
    Your users won't be able to install the package since you don't put out a new build for `osx-arm64`+`python=3.8`.
2. With out those changs:
    Your users won't be able to install the package since they can't install the dependencies for `osx-arm64`+`python=3.8`.

Meaning, the outcome is the same but for option 1 you create additional churn/packages.

----
You should revert the changes -- apart from our maintainership application, if you want.

**Comment by ccordoba12** [comment]
> With your proposed changes:
> Your users won't be able to install the package since you don't put out a new build for osx-arm64+python=3.8

This is already not possible because this package depends on `pyobjc-framework-coreservices`, which needs Python 3.9+.

> With out those changs:
> Your users won't be able to install the package since they can't install the dependencies for osx-arm64+python=3.8

Sure, but what I want is not that combo, as I already mentioned. It's `osx-x64` + `python>=3.8` and `osx-arm64` + `python>=3.9`

> You should revert the changes -- apart from our maintainership application, if you want.

That's really not going to help because then the bot would still be stuck with the solve conflict I posted above.

**Comment by isuruf** [comment]
> That's really not going to help because then the bot would still be stuck with the solve conflict I posted above.

No, the way to fix your solve conflict is to fix your dependencies in https://github.com/conda-forge/spyder-feedstock/blob/565ce8f2310adb174f6f3614e2e38828fb06d2b5/recipe/meta.yaml#L30

**Comment by ccordoba12** [comment]
@isuruf, I guess you mean we should have a more fine-grained selector for this dependency, right?

If so, which one should we use?

**Comment by isuruf** [comment]
> @isuruf, I guess you mean we should have a more fine-grained selector for this dependency, right?

Yes. You should use the conditions you used here.

**Comment by ccordoba12** [comment]
Ok, thanks @isuruf for your help! Will do.

**Comment by mbargull** [comment]
> > @isuruf, I guess you mean we should have a more fine-grained selector for this dependency, right?
> 
> Yes. You should use the conditions you used here.

Correct -- unless it is meant to be hard dependency for all `osx` builds. In that case you'd need to add `skip` to `spyder` with the selectors.

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
So, the right selector is this one?

    # [(osx and x64 and py >= 3.8) or (osx and arm64 and py >= 3.9)]

**Comment by isuruf** [comment]
```
# [(osx and x86_64 and py >= 38) or (osx and arm64 and py >= 39)]
```
or simply
```
# [osx and (x86_64 or (arm64 and py >= 39))]
```

**Comment by mbargull** [comment]
But to make sure you understand:
With that selector, you'd still get `spyder` builds for `osx-arm64` and `python=3.8` but those will simply not depend on `applaunchservices` (i.e., `spyder`'s dependencies will be slightly inconsistent between the different builds for `osx-arm64`).
(Since I don't know anything about `spyder`'s deps, I can't say if that's reasonable or not.)

**Comment by ccordoba12** [comment]
Sure, I understand that. But in that case I think we should simply skip the Python 3.8 builds for Arm64.

**Comment by mbargull** [comment]
> Sure, I understand that. But in that case I think we should simply skip the Python 3.8 builds for Arm64.

Okay. That's what I thought.
Then for `spyder` the exact same as https://github.com/conda-forge/pyobjc-framework-coreservices-feedstock/pull/13#issuecomment-1817705224 applies:
Just add a `skip: true  # [osx and arm64 and py < 39]` or similar.

**Comment by ccordoba12** [comment]
@impact27, this should be ready to be merged.

**Comment by ccordoba12** [comment]
@conda-forge/core, could you merge this one given that one of the feedstock maintainers approved it?

**Pull request merged**
